name: Publish to PyPI.org

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Installing flake8
        run: python3 -m pip install flake8
      - name: Run Lint
        run: flake8
      - name: Run Tests
        run: python -m unittest discover gc_google_services_api/ "test_*.py"
      - name: Creating build
        run: python3 setup.py sdist