name: Publish to PyPI.org

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Lint
        run: make lint
      - name: Run Tests
        run: make test-ci
      - name: Creating build
        run: python3 setup.py sdist