name: Tests and Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Lint
        run: source .venv/bin/activate && make lint

      - name: Run Tests
        run: source .venv/bin/activate && make test

      - name: Creating build
        run: source .venv/bin/activate && poetry build
