name: Publish to PyPI.org

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Lint
        run: make lint

      - name: Run Tests
        run: make test
        
      - name: Creating build
        run: python3 setup.py sdist